// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneBook.Data;

namespace PhoneBook.Data.Migrations
{
    [DbContext(typeof(PhoneBookDbContext))]
    partial class PhoneBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("PhoneBook.Data.ContactModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhoneBookUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhoneBookUserId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2595),
                            FirstName = "Sui",
                            LastName = "Lui",
                            ModifiedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2594),
                            PhoneBookUserId = 1,
                            PhoneNumber = "0817771662"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2766),
                            FirstName = "Jean",
                            LastName = "Jut",
                            ModifiedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2765),
                            PhoneBookUserId = 2,
                            PhoneNumber = "0817819662"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2768),
                            FirstName = "Sam",
                            LastName = "Lam",
                            ModifiedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2767),
                            PhoneBookUserId = 3,
                            PhoneNumber = "0819182662"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2770),
                            FirstName = "Oros",
                            LastName = "Loros",
                            ModifiedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2769),
                            PhoneBookUserId = 4,
                            PhoneNumber = "0817718928"
                        });
                });

            modelBuilder.Entity("PhoneBook.Data.PhoneBookUserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PhoneBook");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2122),
                            FirstName = "Edward",
                            LastName = "Zeyn",
                            ModifiedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(1927)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2282),
                            FirstName = "Simon",
                            LastName = "Gi",
                            ModifiedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2281)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2284),
                            FirstName = "King",
                            LastName = "Kinh",
                            ModifiedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2283)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2285),
                            FirstName = "Frek",
                            LastName = "Lek",
                            ModifiedDate = new DateTime(2021, 6, 29, 20, 33, 17, 129, DateTimeKind.Utc).AddTicks(2285)
                        });
                });

            modelBuilder.Entity("PhoneBook.Data.ContactModel", b =>
                {
                    b.HasOne("PhoneBook.Data.PhoneBookUserModel", "PhoneBookUser")
                        .WithMany("Contacts")
                        .HasForeignKey("PhoneBookUserId");

                    b.Navigation("PhoneBookUser");
                });

            modelBuilder.Entity("PhoneBook.Data.PhoneBookUserModel", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
